/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
package View;
import Controller.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class GerenciamentoFrame extends javax.swing.JFrame{
    GerenciamentoController gerenciamento=new GerenciamentoController();
    ConsultaController consulta=new ConsultaController();
    /**
     * Creates new form GerenciamentoFrame
     */
    public GerenciamentoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameCadastroFunc = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoCpf = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoRua = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoBairro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoNumero = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        campoCidade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoEstado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        campoData = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        btSairCadastro = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        comboCategoria = new javax.swing.JComboBox<>();
        frameCadastroQuarto = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        giratorioNumQuarto = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        campoPreco = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        selecaoAr = new javax.swing.JCheckBox();
        selecaoWifi = new javax.swing.JCheckBox();
        selecaoFrigobar = new javax.swing.JCheckBox();
        btCadastrarQuarto = new javax.swing.JButton();
        btSairQuarto = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        frameListarQuartos = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        btVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListarQuartos = new javax.swing.JTable();
        frameExcluirQuarto = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        campoNumExcluir = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        btCancelarQuarto = new javax.swing.JButton();
        frameListarFuncionarios = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        btVoltarFunc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListarFuncionarios = new javax.swing.JTable();
        frameExcluirFuncionario = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        campoNumExcluirFunc = new javax.swing.JTextField();
        btExcluirFunc = new javax.swing.JButton();
        btCancelarFunc = new javax.swing.JButton();
        frameListarClientes = new javax.swing.JFrame();
        jPanel8 = new javax.swing.JPanel();
        btVoltarCliente = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbListarCliente = new javax.swing.JTable();
        frameExcluirCliente = new javax.swing.JFrame();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        campoNumExcluirCliente = new javax.swing.JTextField();
        btExcluirCli = new javax.swing.JButton();
        btCancelarCliente = new javax.swing.JButton();
        frameGerenciarClientes = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        btExcluirCliente = new javax.swing.JButton();
        btListarClientes = new javax.swing.JButton();
        btVoltarGerCliente = new javax.swing.JButton();
        frameGerenciarFuncionarios = new javax.swing.JFrame();
        jPanel11 = new javax.swing.JPanel();
        btExcluirFuncionario = new javax.swing.JButton();
        btListarFuncionario = new javax.swing.JButton();
        btCadastroFunc = new javax.swing.JButton();
        btVoltarGerFunc = new javax.swing.JButton();
        frameGerenciarQuartos = new javax.swing.JFrame();
        jPanel12 = new javax.swing.JPanel();
        btListarQuartos = new javax.swing.JButton();
        btExcluirQuarto = new javax.swing.JButton();
        btCadastroQuartos = new javax.swing.JButton();
        btVoltarGerQuarto = new javax.swing.JButton();
        painelFundo = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        btEmitir = new javax.swing.JButton();
        btExibirRelatorios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btGerenciarClientes = new javax.swing.JButton();
        btGerenciarFuncionarios = new javax.swing.JButton();
        btGerenciarQuartos = new javax.swing.JButton();

        frameCadastroFunc.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameCadastroFunc.setTitle("Cadastro de funcionários");
        frameCadastroFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        frameCadastroFunc.setLocation(new java.awt.Point(500, 250));
        frameCadastroFunc.setMinimumSize(new java.awt.Dimension(530, 455));
        frameCadastroFunc.setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(480, 450));

        jLabel2.setText("Nome:");

        jLabel3.setText("CPF:");

        jLabel4.setText("Rua:");

        jLabel5.setText("Bairro:");

        jLabel6.setText("Número:");

        jLabel7.setText("Cidade:");

        jLabel9.setText("Estado:");

        jLabel10.setText("Data de nascimento:");

        jLabel12.setText("Telefone:");

        jLabel14.setText("Usuário:");

        jLabel15.setText("Senha:");

        btLimpar.setText("Limpar");
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btSairCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Error-icon.png"))); // NOI18N
        btSairCadastro.setText("Sair");
        btSairCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSairCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairCadastroActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        jLabel21.setText("Categoria:");

        comboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Gerente" }));
        comboCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(campoRua, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addComponent(campoCpf)
                                .addComponent(jLabel2)
                                .addComponent(campoNome))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(campoCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addComponent(campoNumero)
                                .addComponent(jLabel5)
                                .addComponent(campoBairro)))
                        .addContainerGap(275, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(btSairCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel10)
                                        .addComponent(campoData, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addComponent(campoEstado)
                                        .addComponent(campoTelefone))
                                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21))))
                        .addGap(26, 27, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSairCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameCadastroFuncLayout = new javax.swing.GroupLayout(frameCadastroFunc.getContentPane());
        frameCadastroFunc.getContentPane().setLayout(frameCadastroFuncLayout);
        frameCadastroFuncLayout.setHorizontalGroup(
            frameCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameCadastroFuncLayout.setVerticalGroup(
            frameCadastroFuncLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frameCadastroQuarto.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameCadastroQuarto.setTitle("Cadastro de quartos");
        frameCadastroQuarto.setLocation(new java.awt.Point(500, 250));
        frameCadastroQuarto.setMinimumSize(new java.awt.Dimension(300, 500));
        frameCadastroQuarto.setResizable(false);

        jLabel16.setText("Número do quarto:");

        jLabel17.setText("Categoria do quarto:");

        giratorioNumQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Duplo Solteiro", "Casal" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setText("Diária:");

        jLabel11.setText("Ar-Condicionado:");

        jLabel18.setText("Wi-Fi:");

        jLabel19.setText("Frigobar:");

        selecaoAr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        selecaoWifi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        selecaoFrigobar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btCadastrarQuarto.setText("Cadastrar");
        btCadastrarQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastrarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarQuartoActionPerformed(evt);
            }
        });

        btSairQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Error-icon.png"))); // NOI18N
        btSairQuarto.setText("Sair");
        btSairQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSairQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairQuartoActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/quarto.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selecaoFrigobar)
                                    .addComponent(selecaoAr)
                                    .addComponent(selecaoWifi)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(giratorioNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(98, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btCadastrarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btSairQuarto)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(giratorioNumQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(selecaoAr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selecaoWifi))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(selecaoFrigobar))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrarQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSairQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout frameCadastroQuartoLayout = new javax.swing.GroupLayout(frameCadastroQuarto.getContentPane());
        frameCadastroQuarto.getContentPane().setLayout(frameCadastroQuartoLayout);
        frameCadastroQuartoLayout.setHorizontalGroup(
            frameCadastroQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameCadastroQuartoLayout.setVerticalGroup(
            frameCadastroQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCadastroQuartoLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        frameListarQuartos.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameListarQuartos.setTitle("Lista de quartos");
        frameListarQuartos.setLocation(new java.awt.Point(500, 150));
        frameListarQuartos.setMinimumSize(new java.awt.Dimension(714, 315));

        btVoltar.setText("Voltar");
        btVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        tbListarQuartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número do quarto", "Categoria", "Status", "Diária", "Ar-Condicionado", "Wi-fi", "Frigobar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbListarQuartos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 704, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltar)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameListarQuartosLayout = new javax.swing.GroupLayout(frameListarQuartos.getContentPane());
        frameListarQuartos.getContentPane().setLayout(frameListarQuartosLayout);
        frameListarQuartosLayout.setHorizontalGroup(
            frameListarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameListarQuartosLayout.setVerticalGroup(
            frameListarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frameExcluirQuarto.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameExcluirQuarto.setTitle("Excluir quarto");
        frameExcluirQuarto.setLocation(new java.awt.Point(500, 150));
        frameExcluirQuarto.setMinimumSize(new java.awt.Dimension(190, 140));
        frameExcluirQuarto.setResizable(false);

        jLabel22.setText("Número do quarto:");

        btExcluir.setText("Excluir");
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btCancelarQuarto.setText("Cancelar");
        btCancelarQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(campoNumExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelarQuarto)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btCancelarQuarto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameExcluirQuartoLayout = new javax.swing.GroupLayout(frameExcluirQuarto.getContentPane());
        frameExcluirQuarto.getContentPane().setLayout(frameExcluirQuartoLayout);
        frameExcluirQuartoLayout.setHorizontalGroup(
            frameExcluirQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameExcluirQuartoLayout.setVerticalGroup(
            frameExcluirQuartoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frameListarFuncionarios.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameListarFuncionarios.setTitle("Lista de funcionários");
        frameListarFuncionarios.setLocation(new java.awt.Point(500, 150));
        frameListarFuncionarios.setMinimumSize(new java.awt.Dimension(714, 315));

        btVoltarFunc.setText("Voltar");
        btVoltarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarFuncActionPerformed(evt);
            }
        });

        tbListarFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Rua", "Número", "Bairro", "Cidade", "Estado", "Data de nascimento", "Telefone", "Usuário", "Senha", "Nível", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbListarFuncionarios);
        if (tbListarFuncionarios.getColumnModel().getColumnCount() > 0) {
            tbListarFuncionarios.getColumnModel().getColumn(12).setHeaderValue("Código");
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltarFunc))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltarFunc)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameListarFuncionariosLayout = new javax.swing.GroupLayout(frameListarFuncionarios.getContentPane());
        frameListarFuncionarios.getContentPane().setLayout(frameListarFuncionariosLayout);
        frameListarFuncionariosLayout.setHorizontalGroup(
            frameListarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameListarFuncionariosLayout.setVerticalGroup(
            frameListarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frameExcluirFuncionario.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameExcluirFuncionario.setLocation(new java.awt.Point(500, 150));
        frameExcluirFuncionario.setMinimumSize(new java.awt.Dimension(190, 140));
        frameExcluirFuncionario.setResizable(false);

        jLabel24.setText("Código do funcionário:");

        btExcluirFunc.setText("Excluir");
        btExcluirFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFuncActionPerformed(evt);
            }
        });

        btCancelarFunc.setText("Cancelar");
        btCancelarFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(campoNumExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelarFunc)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumExcluirFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluirFunc)
                    .addComponent(btCancelarFunc))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameExcluirFuncionarioLayout = new javax.swing.GroupLayout(frameExcluirFuncionario.getContentPane());
        frameExcluirFuncionario.getContentPane().setLayout(frameExcluirFuncionarioLayout);
        frameExcluirFuncionarioLayout.setHorizontalGroup(
            frameExcluirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameExcluirFuncionarioLayout.setVerticalGroup(
            frameExcluirFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frameListarClientes.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameListarClientes.setTitle("Lista de clientes");
        frameListarClientes.setLocation(new java.awt.Point(500, 150));
        frameListarClientes.setMinimumSize(new java.awt.Dimension(714, 315));

        btVoltarCliente.setText("Voltar");
        btVoltarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarClienteActionPerformed(evt);
            }
        });

        tbListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF/RG", "Rua", "Número", "Bairro", "Cidade", "Estado", "Data de nascimento", "Telefone", "Quarto reservado", "Data da reserva", "codCliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbListarCliente);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btVoltarCliente))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltarCliente)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameListarClientesLayout = new javax.swing.GroupLayout(frameListarClientes.getContentPane());
        frameListarClientes.getContentPane().setLayout(frameListarClientesLayout);
        frameListarClientesLayout.setHorizontalGroup(
            frameListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameListarClientesLayout.setVerticalGroup(
            frameListarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        frameExcluirCliente.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameExcluirCliente.setTitle("Excluir cliente");
        frameExcluirCliente.setLocation(new java.awt.Point(500, 150));
        frameExcluirCliente.setMinimumSize(new java.awt.Dimension(190, 140));
        frameExcluirCliente.setResizable(false);

        jLabel25.setText("Código do cliente:");

        btExcluirCli.setText("Excluir");
        btExcluirCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirCliActionPerformed(evt);
            }
        });

        btCancelarCliente.setText("Cancelar");
        btCancelarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(campoNumExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btExcluirCli, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancelarCliente)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNumExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluirCli)
                    .addComponent(btCancelarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameExcluirClienteLayout = new javax.swing.GroupLayout(frameExcluirCliente.getContentPane());
        frameExcluirCliente.getContentPane().setLayout(frameExcluirClienteLayout);
        frameExcluirClienteLayout.setHorizontalGroup(
            frameExcluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameExcluirClienteLayout.setVerticalGroup(
            frameExcluirClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frameGerenciarClientes.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameGerenciarClientes.setTitle("Gerenciamento de clientes");
        frameGerenciarClientes.setLocation(new java.awt.Point(500, 150));
        frameGerenciarClientes.setMinimumSize(new java.awt.Dimension(200, 160));
        frameGerenciarClientes.setResizable(false);

        btExcluirCliente.setText("Excluir cliente");
        btExcluirCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirClienteActionPerformed(evt);
            }
        });

        btListarClientes.setText("Listar clientes");
        btListarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarClientesActionPerformed(evt);
            }
        });

        btVoltarGerCliente.setText("Voltar");
        btVoltarGerCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarGerCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarGerClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btExcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltarGerCliente)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btVoltarGerCliente)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameGerenciarClientesLayout = new javax.swing.GroupLayout(frameGerenciarClientes.getContentPane());
        frameGerenciarClientes.getContentPane().setLayout(frameGerenciarClientesLayout);
        frameGerenciarClientesLayout.setHorizontalGroup(
            frameGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frameGerenciarClientesLayout.setVerticalGroup(
            frameGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frameGerenciarFuncionarios.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameGerenciarFuncionarios.setTitle("Gerenciamento de funcionários");
        frameGerenciarFuncionarios.setLocation(new java.awt.Point(500, 150));
        frameGerenciarFuncionarios.setMinimumSize(new java.awt.Dimension(225, 220));
        frameGerenciarFuncionarios.setResizable(false);

        btExcluirFuncionario.setText("Excluir funcionário");
        btExcluirFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirFuncionarioActionPerformed(evt);
            }
        });

        btListarFuncionario.setText("Listar funcionários");
        btListarFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarFuncionarioActionPerformed(evt);
            }
        });

        btCadastroFunc.setText("Cadastrar funcionário");
        btCadastroFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroFuncActionPerformed(evt);
            }
        });

        btVoltarGerFunc.setText("Voltar");
        btVoltarGerFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarGerFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarGerFuncActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btListarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btCadastroFunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluirFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltarGerFunc)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCadastroFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btListarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btVoltarGerFunc)
                .addContainerGap())
        );

        javax.swing.GroupLayout frameGerenciarFuncionariosLayout = new javax.swing.GroupLayout(frameGerenciarFuncionarios.getContentPane());
        frameGerenciarFuncionarios.getContentPane().setLayout(frameGerenciarFuncionariosLayout);
        frameGerenciarFuncionariosLayout.setHorizontalGroup(
            frameGerenciarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameGerenciarFuncionariosLayout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frameGerenciarFuncionariosLayout.setVerticalGroup(
            frameGerenciarFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frameGerenciarQuartos.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameGerenciarQuartos.setTitle("Gerenciamento de quartos");
        frameGerenciarQuartos.setLocation(new java.awt.Point(500, 150));
        frameGerenciarQuartos.setMinimumSize(new java.awt.Dimension(208, 245));
        frameGerenciarQuartos.setResizable(false);

        btListarQuartos.setText("Listar quartos");
        btListarQuartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btListarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarQuartosActionPerformed(evt);
            }
        });

        btExcluirQuarto.setText("Excluir quarto");
        btExcluirQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExcluirQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirQuartoActionPerformed(evt);
            }
        });

        btCadastroQuartos.setText("Cadastrar quarto");
        btCadastroQuartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btCadastroQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastroQuartosActionPerformed(evt);
            }
        });

        btVoltarGerQuarto.setText("Voltar");
        btVoltarGerQuarto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVoltarGerQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarGerQuartoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCadastroQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btListarQuartos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btExcluirQuarto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btVoltarGerQuarto)
                .addGap(23, 23, 23))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btCadastroQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btListarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btExcluirQuarto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVoltarGerQuarto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameGerenciarQuartosLayout = new javax.swing.GroupLayout(frameGerenciarQuartos.getContentPane());
        frameGerenciarQuartos.getContentPane().setLayout(frameGerenciarQuartosLayout);
        frameGerenciarQuartosLayout.setHorizontalGroup(
            frameGerenciarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameGerenciarQuartosLayout.setVerticalGroup(
            frameGerenciarQuartosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Gerenciamento");
        setLocation(new java.awt.Point(500, 250));
        setResizable(false);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Error-icon.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btEmitir.setText("Emitir relatórios");
        btEmitir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btExibirRelatorios.setText("Exibir relatórios");
        btExibirRelatorios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btExibirRelatorios.setMaximumSize(new java.awt.Dimension(113, 23));
        btExibirRelatorios.setMinimumSize(new java.awt.Dimension(113, 23));
        btExibirRelatorios.setPreferredSize(new java.awt.Dimension(113, 23));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconmonstr-gear-10-icon-256.png"))); // NOI18N

        btGerenciarClientes.setText("Gerenciar clientes");
        btGerenciarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerenciarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarClientesActionPerformed(evt);
            }
        });

        btGerenciarFuncionarios.setText("Gerenciar funcionários");
        btGerenciarFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerenciarFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarFuncionariosActionPerformed(evt);
            }
        });

        btGerenciarQuartos.setText("Gerenciar quartos");
        btGerenciarQuartos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerenciarQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciarQuartosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btEmitir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btGerenciarQuartos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btExibirRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btGerenciarClientes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btGerenciarFuncionarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(painelFundoLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btSair)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btExibirRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGerenciarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGerenciarFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGerenciarQuartos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCadastroFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroFuncActionPerformed
        frameCadastroFunc.setVisible(true);
    }//GEN-LAST:event_btCadastroFuncActionPerformed

    private void btCadastroQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastroQuartosActionPerformed
        frameCadastroQuarto.setVisible(true);
    }//GEN-LAST:event_btCadastroQuartosActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        try{
            gerenciamento.cadastrarFuncionario(this.campoNome.getText(), this.campoCpf.getText(), this.campoRua.getText(), this.campoBairro.getText(), 
                    Integer.parseInt(this.campoNumero.getText()), this.campoCidade.getText(), this.campoEstado.getText(),
                    this.campoData.getText(),this.campoTelefone.getText(),this.campoUsuario.getText(), this.campoSenha.getText(), 
                    String.valueOf(this.comboCategoria.getSelectedItem()));
            frameCadastroFunc.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Campos inválidos ou preenchidos incorretamente!");
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        this.campoNome.setText("");
        this.campoRua.setText("");
        this.campoBairro.setText("");
        this.campoNumero.setText("");
        this.campoCidade.setText("");
        this.campoEstado.setText("");
        this.campoData.setText("");
        this.campoTelefone.setText("");
        this.campoUsuario.setText("");
        this.campoSenha.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairQuartoActionPerformed
        frameCadastroQuarto.dispose();
    }//GEN-LAST:event_btSairQuartoActionPerformed

    private void btCadastrarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarQuartoActionPerformed
        int selecaoArInt,selecaoWifiInt,selecaoFrigobarInt;
        int valorSpinner=Integer.parseInt(this.giratorioNumQuarto.getValue().toString());
        if(this.selecaoAr.isSelected()){
            selecaoArInt=1;
        }
        else{
            selecaoArInt=0;
        }
        if(this.selecaoWifi.isSelected()){
            selecaoWifiInt=1;
        }
        else{
            selecaoWifiInt=0;
        }
        if(this.selecaoFrigobar.isSelected()){
            selecaoFrigobarInt=1;
        }
        else{
            selecaoFrigobarInt=0;
        }
        try{
            this.gerenciamento.cadastrarQuarto(valorSpinner,String.valueOf(this.jComboBox1.getSelectedItem()),"Desocupado",
                    Double.parseDouble(this.campoPreco.getText()),selecaoArInt,selecaoWifiInt,selecaoFrigobarInt);
            this.frameCadastroQuarto.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Campos inválidos ou preenchidos incorretamente!");
        }
    }//GEN-LAST:event_btCadastrarQuartoActionPerformed

    private void btSairCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairCadastroActionPerformed
        frameCadastroFunc.dispose();
    }//GEN-LAST:event_btSairCadastroActionPerformed

    private void btExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFuncionarioActionPerformed
        this.frameExcluirFuncionario.setVisible(true);
    }//GEN-LAST:event_btExcluirFuncionarioActionPerformed

    private void btListarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarQuartosActionPerformed
        String resultados[][]=consulta.listarQuartos();
        this.frameListarQuartos.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tbListarQuartos.getModel();
        for(int i=0;i<resultados.length;i++){
            model.addRow(new Object[]{resultados[i][0],resultados[i][1],resultados[i][2],resultados[i][3],resultados[i][4],resultados[i][5],resultados[i][6]});
        }
    }//GEN-LAST:event_btListarQuartosActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        while(tbListarQuartos.getModel().getRowCount()>0){
            ((DefaultTableModel)tbListarQuartos.getModel()).removeRow(0);
        }
        this.frameListarQuartos.dispose();
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btExcluirQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirQuartoActionPerformed
        this.frameExcluirQuarto.setVisible(true);
    }//GEN-LAST:event_btExcluirQuartoActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try{
            gerenciamento.excluirQuarto(Integer.parseInt(this.campoNumExcluir.getText()));
            this.frameExcluirQuarto.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não existe um quarto com esse número!");
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btCancelarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarQuartoActionPerformed
        this.frameExcluirQuarto.dispose();
    }//GEN-LAST:event_btCancelarQuartoActionPerformed

    private void btVoltarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarFuncActionPerformed
        while(tbListarFuncionarios.getModel().getRowCount()>0){
            ((DefaultTableModel)tbListarFuncionarios.getModel()).removeRow(0);
        }
        this.frameListarFuncionarios.dispose();
    }//GEN-LAST:event_btVoltarFuncActionPerformed

    private void btListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarFuncionarioActionPerformed
        String resultados[][]=consulta.listarFuncionarios();
        this.frameListarFuncionarios.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tbListarFuncionarios.getModel();
        for(int i=0;i<resultados.length;i++){
            model.addRow(new Object[]{resultados[i][0],resultados[i][1],resultados[i][2],resultados[i][3],resultados[i][4],resultados[i][5]
                    ,resultados[i][6],resultados[i][7],resultados[i][8],resultados[i][9],resultados[i][10],resultados[i][11],resultados[i][12]});
        }
    }//GEN-LAST:event_btListarFuncionarioActionPerformed

    private void btExcluirFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFuncActionPerformed
        try{
            this.gerenciamento.excluirFuncionario(Integer.parseInt(this.campoNumExcluirFunc.getText()));
            this.frameExcluirFuncionario.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não existe um funcionário com esse código!");
        }
    }//GEN-LAST:event_btExcluirFuncActionPerformed

    private void btCancelarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarFuncActionPerformed
        this.frameExcluirFuncionario.dispose();
    }//GEN-LAST:event_btCancelarFuncActionPerformed

    private void btListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarClientesActionPerformed
       String resultados[][]=consulta.listarClientes();
        this.frameListarClientes.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tbListarCliente.getModel();
        for(int i=0;i<resultados.length;i++){
            model.addRow(new Object[]{resultados[i][0],resultados[i][1],resultados[i][2],resultados[i][3],resultados[i][4],resultados[i][5]
                    ,resultados[i][6],resultados[i][7],resultados[i][8],resultados[i][9],resultados[i][10],resultados[i][11]});
        }
    }//GEN-LAST:event_btListarClientesActionPerformed

    private void btVoltarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarClienteActionPerformed
        while(tbListarCliente.getModel().getRowCount()>0){
            ((DefaultTableModel)tbListarCliente.getModel()).removeRow(0);
        }
        this.frameListarClientes.dispose();
    }//GEN-LAST:event_btVoltarClienteActionPerformed

    private void btExcluirCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirCliActionPerformed
        try{
            this.gerenciamento.excluirCliente(Integer.parseInt(this.campoNumExcluirCliente.getText()));
            this.frameExcluirCliente.dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Não existe um cliente com esse código!");
        }
        
    }//GEN-LAST:event_btExcluirCliActionPerformed

    private void btCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarClienteActionPerformed
        this.frameExcluirCliente.dispose();
    }//GEN-LAST:event_btCancelarClienteActionPerformed

    private void btExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirClienteActionPerformed
        this.frameExcluirCliente.setVisible(true);
    }//GEN-LAST:event_btExcluirClienteActionPerformed

    private void btVoltarGerClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarGerClienteActionPerformed
        this.frameGerenciarClientes.dispose();
    }//GEN-LAST:event_btVoltarGerClienteActionPerformed

    private void btGerenciarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarClientesActionPerformed
        this.frameGerenciarClientes.setVisible(true);
    }//GEN-LAST:event_btGerenciarClientesActionPerformed

    private void btVoltarGerFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarGerFuncActionPerformed
        this.frameGerenciarFuncionarios.dispose();
    }//GEN-LAST:event_btVoltarGerFuncActionPerformed

    private void btGerenciarFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarFuncionariosActionPerformed
        this.frameGerenciarFuncionarios.setVisible(true);
    }//GEN-LAST:event_btGerenciarFuncionariosActionPerformed

    private void btGerenciarQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciarQuartosActionPerformed
        this.frameGerenciarQuartos.setVisible(true);
    }//GEN-LAST:event_btGerenciarQuartosActionPerformed

    private void btVoltarGerQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarGerQuartoActionPerformed
        this.frameGerenciarQuartos.dispose();
    }//GEN-LAST:event_btVoltarGerQuartoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the
        Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCadastrarQuarto;
    private javax.swing.JButton btCadastroFunc;
    private javax.swing.JButton btCadastroQuartos;
    private javax.swing.JButton btCancelarCliente;
    private javax.swing.JButton btCancelarFunc;
    private javax.swing.JButton btCancelarQuarto;
    private javax.swing.JButton btEmitir;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluirCli;
    private javax.swing.JButton btExcluirCliente;
    private javax.swing.JButton btExcluirFunc;
    private javax.swing.JButton btExcluirFuncionario;
    private javax.swing.JButton btExcluirQuarto;
    private javax.swing.JButton btExibirRelatorios;
    private javax.swing.JButton btGerenciarClientes;
    private javax.swing.JButton btGerenciarFuncionarios;
    private javax.swing.JButton btGerenciarQuartos;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btListarClientes;
    private javax.swing.JButton btListarFuncionario;
    private javax.swing.JButton btListarQuartos;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSairCadastro;
    private javax.swing.JButton btSairQuarto;
    private javax.swing.JButton btVoltar;
    private javax.swing.JButton btVoltarCliente;
    private javax.swing.JButton btVoltarFunc;
    private javax.swing.JButton btVoltarGerCliente;
    private javax.swing.JButton btVoltarGerFunc;
    private javax.swing.JButton btVoltarGerQuarto;
    private javax.swing.JTextField campoBairro;
    private javax.swing.JTextField campoCidade;
    private javax.swing.JTextField campoCpf;
    private javax.swing.JTextField campoData;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoNumExcluir;
    private javax.swing.JTextField campoNumExcluirCliente;
    private javax.swing.JTextField campoNumExcluirFunc;
    private javax.swing.JTextField campoNumero;
    private javax.swing.JTextField campoPreco;
    private javax.swing.JTextField campoRua;
    private javax.swing.JTextField campoSenha;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JComboBox<String> comboCategoria;
    private javax.swing.JFrame frameCadastroFunc;
    private javax.swing.JFrame frameCadastroQuarto;
    private javax.swing.JFrame frameExcluirCliente;
    private javax.swing.JFrame frameExcluirFuncionario;
    private javax.swing.JFrame frameExcluirQuarto;
    private javax.swing.JFrame frameGerenciarClientes;
    private javax.swing.JFrame frameGerenciarFuncionarios;
    private javax.swing.JFrame frameGerenciarQuartos;
    private javax.swing.JFrame frameListarClientes;
    private javax.swing.JFrame frameListarFuncionarios;
    private javax.swing.JFrame frameListarQuartos;
    private javax.swing.JSpinner giratorioNumQuarto;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JCheckBox selecaoAr;
    private javax.swing.JCheckBox selecaoFrigobar;
    private javax.swing.JCheckBox selecaoWifi;
    private javax.swing.JTable tbListarCliente;
    private javax.swing.JTable tbListarFuncionarios;
    private javax.swing.JTable tbListarQuartos;
    // End of variables declaration//GEN-END:variables
}
