/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
package View;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Controller.ConsultaController;
public class InterfacePrincipal extends javax.swing.JFrame {
    ConsultaController consultas=new ConsultaController();
    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        setExtendedState(MAXIMIZED_BOTH);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msgSair = new javax.swing.JDialog();
        painelSair = new javax.swing.JPanel();
        btSim = new javax.swing.JButton();
        btNao = new javax.swing.JButton();
        frameNivel = new javax.swing.JFrame();
        painelFundo = new javax.swing.JPanel();
        btSair1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        btAbrirGerenciamento = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();
        btConsulta = new javax.swing.JButton();
        btReserva = new javax.swing.JButton();
        btGerenciamento = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btAlternar = new javax.swing.JButton();
        menuGeral = new javax.swing.JMenuBar();
        menuConsulta = new javax.swing.JMenu();
        menuConsultar = new javax.swing.JMenuItem();
        menuHospedar = new javax.swing.JMenuItem();
        menuGerenciamento = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();

        msgSair.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        msgSair.setTitle("Deseja realmente sair?");
        msgSair.setLocation(new java.awt.Point(500, 250));
        msgSair.setMinimumSize(new java.awt.Dimension(190, 90));
        msgSair.setResizable(false);

        painelSair.setPreferredSize(new java.awt.Dimension(45, 45));

        btSim.setText("Sim");
        btSim.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimActionPerformed(evt);
            }
        });

        btNao.setText("Não");
        btNao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelSairLayout = new javax.swing.GroupLayout(painelSair);
        painelSair.setLayout(painelSairLayout);
        painelSairLayout.setHorizontalGroup(
            painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelSairLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btSim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btNao)
                .addGap(24, 24, 24))
        );
        painelSairLayout.setVerticalGroup(
            painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelSairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSim)
                    .addComponent(btNao))
                .addContainerGap())
        );

        javax.swing.GroupLayout msgSairLayout = new javax.swing.GroupLayout(msgSair.getContentPane());
        msgSair.getContentPane().setLayout(msgSairLayout);
        msgSairLayout.setHorizontalGroup(
            msgSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSair, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );
        msgSairLayout.setVerticalGroup(
            msgSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        frameNivel.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        frameNivel.setTitle("Nivel");
        frameNivel.setLocation(new java.awt.Point(500, 250));
        frameNivel.setMinimumSize(new java.awt.Dimension(362, 360));
        frameNivel.setPreferredSize(new java.awt.Dimension(362, 360));
        frameNivel.setResizable(false);

        painelFundo.setMinimumSize(new java.awt.Dimension(362, 360));
        painelFundo.setPreferredSize(new java.awt.Dimension(362, 360));

        btSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Error-icon.png"))); // NOI18N
        btSair1.setText("Sair");
        btSair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSair1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome de usuário:");

        jLabel3.setText("Senha:");

        campoSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoSenhaKeyPressed(evt);
            }
        });

        btAbrirGerenciamento.setText("Acessar Gerenciamento");
        btAbrirGerenciamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAbrirGerenciamento.setPreferredSize(new java.awt.Dimension(87, 41));
        btAbrirGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbrirGerenciamentoActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.png"))); // NOI18N

        javax.swing.GroupLayout painelFundoLayout = new javax.swing.GroupLayout(painelFundo);
        painelFundo.setLayout(painelFundoLayout);
        painelFundoLayout.setHorizontalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelFundoLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(painelFundoLayout.createSequentialGroup()
                            .addComponent(btAbrirGerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                            .addComponent(btSair1))
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoSenha, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        painelFundoLayout.setVerticalGroup(
            painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(painelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSair1)
                    .addComponent(btAbrirGerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameNivelLayout = new javax.swing.GroupLayout(frameNivel.getContentPane());
        frameNivel.getContentPane().setLayout(frameNivelLayout);
        frameNivelLayout.setHorizontalGroup(
            frameNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        frameNivelLayout.setVerticalGroup(
            frameNivelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu Principal");
        setLocation(new java.awt.Point(10, 10));

        painelPrincipal.setToolTipText("");

        btConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/consulta.png"))); // NOI18N
        btConsulta.setText("Consulta de quartos");
        btConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        btReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icon-reserve.png"))); // NOI18N
        btReserva.setText("Reservar quarto");
        btReserva.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReserva.setMaximumSize(new java.awt.Dimension(389, 265));
        btReserva.setMinimumSize(new java.awt.Dimension(389, 265));
        btReserva.setPreferredSize(new java.awt.Dimension(389, 265));
        btReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReservaActionPerformed(evt);
            }
        });

        btGerenciamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/iconmonstr-gear-10-icon-256.png"))); // NOI18N
        btGerenciamento.setText("Gerenciamento");
        btGerenciamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btGerenciamento.setMaximumSize(new java.awt.Dimension(389, 265));
        btGerenciamento.setMinimumSize(new java.awt.Dimension(389, 265));
        btGerenciamento.setPreferredSize(new java.awt.Dimension(389, 265));
        btGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenciamentoActionPerformed(evt);
            }
        });

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Error-icon.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/hotel.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        btAlternar.setText("Alternar usuário");
        btAlternar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAlternar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlternarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btReserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btGerenciamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAlternar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair)))
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(btConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(35, 35, 35)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btGerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlternar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        menuGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menuConsulta.setText("Arquivo");
        menuConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuConsultar.setText("Consulta de quartos");
        menuConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultarActionPerformed(evt);
            }
        });
        menuConsulta.add(menuConsultar);

        menuHospedar.setText("Reservar quarto");
        menuHospedar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuHospedar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHospedarActionPerformed(evt);
            }
        });
        menuConsulta.add(menuHospedar);

        menuGerenciamento.setText("Gerenciamento");
        menuGerenciamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuGerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenciamentoActionPerformed(evt);
            }
        });
        menuConsulta.add(menuGerenciamento);

        menuSair.setText("Sair");
        menuSair.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuConsulta.add(menuSair);

        menuGeral.add(menuConsulta);

        menuAjuda.setText("Ajuda");
        menuAjuda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuSobre.setText("Sobre");
        menuSobre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(menuSobre);

        menuGeral.add(menuAjuda);

        setJMenuBar(menuGeral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        msgSair.setVisible(true);
    }//GEN-LAST:event_btSairActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        ConsultaQuartos exibir=new ConsultaQuartos();
        exibir.setVisible(true);
    }//GEN-LAST:event_btConsultaActionPerformed

    private void menuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultarActionPerformed
        btConsultaActionPerformed(evt);
    }//GEN-LAST:event_menuConsultarActionPerformed

    private void btReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReservaActionPerformed
        ReservaFrame exibir=new ReservaFrame();
        exibir.frameConsulta.setVisible(true);
    }//GEN-LAST:event_btReservaActionPerformed

    private void menuHospedarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHospedarActionPerformed
        btReservaActionPerformed(evt);
    }//GEN-LAST:event_menuHospedarActionPerformed
    
    private void btGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenciamentoActionPerformed
        frameNivel.setVisible(true);
    }//GEN-LAST:event_btGerenciamentoActionPerformed

    private void menuGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenciamentoActionPerformed
        btGerenciamentoActionPerformed(evt);
    }//GEN-LAST:event_menuGerenciamentoActionPerformed

    private void btSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimActionPerformed
        msgSair.dispose();
        this.dispose();
    }//GEN-LAST:event_btSimActionPerformed

    private void btNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNaoActionPerformed
        msgSair.dispose();
    }//GEN-LAST:event_btNaoActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        this.btSairActionPerformed(evt);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
         JOptionPane.showMessageDialog(null,"Projeto de Laboratorio de Programação");
    }//GEN-LAST:event_menuSobreActionPerformed

    private void btAlternarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlternarActionPerformed
        InterfaceLogin alternar=new InterfaceLogin();
        alternar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btAlternarActionPerformed

    private void btSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSair1ActionPerformed
        frameNivel.dispose();
    }//GEN-LAST:event_btSair1ActionPerformed

    private void campoSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoSenhaKeyPressed

    }//GEN-LAST:event_campoSenhaKeyPressed

    private void btAbrirGerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbrirGerenciamentoActionPerformed
        String password=String.valueOf(campoSenha.getPassword());
        if(consultas.consultarNivel(this.campoUsuario.getText(), password)){
            GerenciamentoFrame abrir=new GerenciamentoFrame();
            abrir.setVisible(true);
            this.campoUsuario.setText("");
            this.campoSenha.setText("");
            frameNivel.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"Você não tem permissão para entrar nessa área!");
        }
    }//GEN-LAST:event_btAbrirGerenciamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfacePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbrirGerenciamento;
    private javax.swing.JButton btAlternar;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btGerenciamento;
    private javax.swing.JButton btNao;
    private javax.swing.JButton btReserva;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btSair1;
    private javax.swing.JButton btSim;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JFrame frameNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuConsulta;
    private javax.swing.JMenuItem menuConsultar;
    private javax.swing.JMenuBar menuGeral;
    private javax.swing.JMenuItem menuGerenciamento;
    private javax.swing.JMenuItem menuHospedar;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JDialog msgSair;
    private javax.swing.JPanel painelFundo;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelSair;
    // End of variables declaration//GEN-END:variables
}
